services:
  server:
    env_file:
      - .env.prod
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    container_name: server
    ports:
      - 3000:3000
    volumes:
      - avatars_data:/app/backend/public/avatars
    depends_on:
      - database
    environment:
      MONGO_URI: ${MONGO_URI}
    networks:
      - celeste
  database:
    image: mongo:8.0
    ports:
      - 27017:27017
    command: [ "--bind_ip_all", "--port", "27017"]
    volumes:
      - "../celeste-server/mongo_data:/data/db"
      - "../celeste-server/mongo_config:/data/configdb"
    environment:
      MONGO_INITDB_DATABASE: myDb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - celeste
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    depends_on:
     - server
    ports:
     - 80:80
     - 443:443
    networks:
     - celeste

  backup:
    image: mongo:8.0
    container_name: backup
    networks:
      - celeste
    volumes:
      - ./mongo_backups:/backups
      - ./scripts/backup_mongo.sh:/backup.sh
    environment:
      MONGO_URI: mongodb://root:randomString@database:27017/myDb?authSource=admin
    depends_on:
      - database
    command: ["sh", "-c", "chmod +x /backup.sh && /backup.sh"]
    restart: "no"

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - celeste
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email nicolas.m.gardet@gmail.com -d celeste-app.fr --agree-tos
      
networks:
  celeste:
    external: true

volumes:
  avatars_data:
    driver: local


